server:
  port: 9090

# Configuration for api key endpoint
api:
  key:
    endpoint: http://127.0.0.1:9091/apikey

spring:
  security:
    oauth2:
      client:
        registration:
          apikey-client-oidc:
            provider: spring
            client-id: apikey-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: apikey-client-oidc
          apikey-client-authorization-code:
            provider: spring
            client-id: apikey-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/authorized"
            scope: apikey.read
            client-name: apikey-client-authorization-code
        provider:
          spring:
            issuer-uri: http://uaa-server:9000

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN