server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://uaa-server:9000
        client:
          apikey-client:
            registration:
              client-id: apikey-client
              client-secret: "{noop}secret"
              client-name: API Key Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:9090/login/oauth2/code/apikey-client-oidc
                - http://127.0.0.1:9090/authorized
              scopes:
                - openid
                - apikey.read
